Object.createElement;
Object.createElement.apply;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
Object.Fragment;
Object.Children;
Object.Children.toArray;
Object.unmountComponentAtNode;
Object.render;
Object.findDOMNode;
var setTimeout;
var process;
process.hrtime;
var Java;
Java.type;
HTMLDocument.prototype.getElementById;
